### ISSUE TITLE
Morning Session code review

### ISSUE THREAD

**Issue by Lameck1** [toliboff/bookman#3]
Hello @toliboff,

What a wonderful codebase. Your methods are short, descriptive, and of single responsibility.

#### Suggestion
Consider refactoring your CSS to be DRYier 👇🏼.

### Example code
```CSS
.d-flex {
  display: flex;
  align-items: center;
}
```

Then apply this class to HTML element that needs this behavior:

```HTML
  <section class="d-flex">
```
